name: Infrastructure

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .editorconfig
      - .gitignore
      - .gitattributes
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  validate:
    name: Validate IaC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Bicep Lint
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az bicep build --file infrastructure/main.bicep

      - name: Bicep Validate
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az deployment group validate \
              --name validate-${{ github.run_id }} \
              --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
              --template-file infrastructure/main.bicep
              --parameters main.development.bicepparam

  deploy-dry-run:
    name: Deploy Infrastructure (Dry Run)
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Infrastructure (Dry Run)
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az deployment group what-if \
              --name whatif-${{ github.run_id }} \
              --resource-group ${{ vars.AZURE_RESOURCE_GROUP }} \
              --template-file infrastructure/main.bicep \
              --parameters main.development.bicepparam
